CREATE TABLE TAB_DEPARTAMENTO (
    NUM_DEPARTAMENTO NUMBER (10),
    NOM_DEPARTAMENTO VARCHAR2 (100),
    NUM_NSS_GERENTE NUMBER (10),
    DTA_INICIO_GERENCIA DATE,
    CONSTRAINT PK_DEPTO PRIMARY KEY (NUM_DEPARTAMENTO),
    CONSTRAINT UN_DEPTO_NOMDEPTO UNIQUE (NOM_DEPARTAMENTO)
);

CREATE TABLE TAB_EMPREGADO (
    NUM_NSS_EMPREGADO NUMBER (10),
    DSC_ENDERECO VARCHAR2 (100),
    VAL_SALARIO NUMBER (12,2),
    TIP_SEXO CHAR (1),
    DTA_NASCIMENTO DATE,
    NOM_EMPREGADO VARCHAR2 (100),
    NUM_DEPARTAMENTO NUMBER (10),
    NUM_NSS_SUPERVISOR NUMBER (10),
    CONSTRAINT PK_EMPREGADO PRIMARY KEY (NUM_NSS_EMPREGADO)
);

-- ALTERAÇÕES (ESQUECIDAS)
ALTER TABLE TAB_DEPARTAMENTO
ADD QTD_EMPREGADOS NUMBER (10) DEFAULT 0;

ALTER TABLE TAB_EMPREGADO
MODIFY TIP_SEXO CHAR (1) DEFAULT 'N';

-- ALTERAÇÕES NECESSÁRIAS

ALTER TABLE TAB_DEPARTAMENTO
ADD CONSTRAINT FK_EMPREGADO_DEPARTAMENTO FOREIGN KEY (NUM_NSS_GERENTE) 
REFERENCES TAB_EMPREGADO (NUM_NSS_EMPREGADO);

ALTER TABLE TAB_EMPREGADO
ADD CONSTRAINT FK_DEPARTAMENTO_EMPREGADO FOREIGN KEY (NUM_DEPARTAMENTO)
REFERENCES TAB_DEPARTAMENTO (NUM_DEPARTAMENTO);

ALTER TABLE TAB_EMPREGADO
ADD CONSTRAINT FK_EMPREGADO_EMPREGADO FOREIGN KEY (NUM_NSS_EMPREGADO)
REFERENCES TAB_EMPREGADO (NUM_NSS_EMPREGADO);